// Generated by gencpp from file tr5_kinematics/DoForwardKinematic.msg
// DO NOT EDIT!


#ifndef TR5_KINEMATICS_MESSAGE_DOFORWARDKINEMATIC_H
#define TR5_KINEMATICS_MESSAGE_DOFORWARDKINEMATIC_H

#include <ros/service_traits.h>


#include <tr5_kinematics/DoForwardKinematicRequest.h>
#include <tr5_kinematics/DoForwardKinematicResponse.h>


namespace tr5_kinematics
{

struct DoForwardKinematic
{

typedef DoForwardKinematicRequest Request;
typedef DoForwardKinematicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DoForwardKinematic
} // namespace tr5_kinematics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tr5_kinematics::DoForwardKinematic > {
  static const char* value()
  {
    return "20d24d0bf00b897e2f0a8ed596d36c4d";
  }

  static const char* value(const ::tr5_kinematics::DoForwardKinematic&) { return value(); }
};

template<>
struct DataType< ::tr5_kinematics::DoForwardKinematic > {
  static const char* value()
  {
    return "tr5_kinematics/DoForwardKinematic";
  }

  static const char* value(const ::tr5_kinematics::DoForwardKinematic&) { return value(); }
};


// service_traits::MD5Sum< ::tr5_kinematics::DoForwardKinematicRequest> should match 
// service_traits::MD5Sum< ::tr5_kinematics::DoForwardKinematic > 
template<>
struct MD5Sum< ::tr5_kinematics::DoForwardKinematicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tr5_kinematics::DoForwardKinematic >::value();
  }
  static const char* value(const ::tr5_kinematics::DoForwardKinematicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tr5_kinematics::DoForwardKinematicRequest> should match 
// service_traits::DataType< ::tr5_kinematics::DoForwardKinematic > 
template<>
struct DataType< ::tr5_kinematics::DoForwardKinematicRequest>
{
  static const char* value()
  {
    return DataType< ::tr5_kinematics::DoForwardKinematic >::value();
  }
  static const char* value(const ::tr5_kinematics::DoForwardKinematicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tr5_kinematics::DoForwardKinematicResponse> should match 
// service_traits::MD5Sum< ::tr5_kinematics::DoForwardKinematic > 
template<>
struct MD5Sum< ::tr5_kinematics::DoForwardKinematicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tr5_kinematics::DoForwardKinematic >::value();
  }
  static const char* value(const ::tr5_kinematics::DoForwardKinematicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tr5_kinematics::DoForwardKinematicResponse> should match 
// service_traits::DataType< ::tr5_kinematics::DoForwardKinematic > 
template<>
struct DataType< ::tr5_kinematics::DoForwardKinematicResponse>
{
  static const char* value()
  {
    return DataType< ::tr5_kinematics::DoForwardKinematic >::value();
  }
  static const char* value(const ::tr5_kinematics::DoForwardKinematicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TR5_KINEMATICS_MESSAGE_DOFORWARDKINEMATIC_H
