(cl:in-package riverwatch_locomotion-msg)
(cl:export '(HEADER-VAL
          HEADER
          NAME-VAL
          NAME
          PIDE-VAL
          PIDE
          SET_POINT-VAL
          SET_POINT
          PROCESS_VALUE-VAL
          PROCESS_VALUE
          ERROR-VAL
          ERROR
          TIME_STEP-VAL
          TIME_STEP
          COMMAND-VAL
          COMMAND
          P-VAL
          P
          I-VAL
          I
          D-VAL
          D
          INTEGRATOR-VAL
          INTEGRATOR
          DERVATIVE-VAL
          DERVATIVE
          PROPORTIONAL-VAL
          PROPORTIONAL
))