// Generated by gencpp from file riverwatch_locomotion/PidControllerState.msg
// DO NOT EDIT!


#ifndef RIVERWATCH_LOCOMOTION_MESSAGE_PIDCONTROLLERSTATE_H
#define RIVERWATCH_LOCOMOTION_MESSAGE_PIDCONTROLLERSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace riverwatch_locomotion
{
template <class ContainerAllocator>
struct PidControllerState_
{
  typedef PidControllerState_<ContainerAllocator> Type;

  PidControllerState_()
    : header()
    , name()
    , PIDE(false)
    , set_point(0.0)
    , process_value(0.0)
    , error(0.0)
    , time_step(0.0)
    , command(0.0)
    , p(0.0)
    , i(0.0)
    , d(0.0)
    , integrator(0.0)
    , dervative(0.0)
    , proportional(0.0)  {
    }
  PidControllerState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , PIDE(false)
    , set_point(0.0)
    , process_value(0.0)
    , error(0.0)
    , time_step(0.0)
    , command(0.0)
    , p(0.0)
    , i(0.0)
    , d(0.0)
    , integrator(0.0)
    , dervative(0.0)
    , proportional(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _PIDE_type;
  _PIDE_type PIDE;

   typedef double _set_point_type;
  _set_point_type set_point;

   typedef double _process_value_type;
  _process_value_type process_value;

   typedef double _error_type;
  _error_type error;

   typedef double _time_step_type;
  _time_step_type time_step;

   typedef double _command_type;
  _command_type command;

   typedef double _p_type;
  _p_type p;

   typedef double _i_type;
  _i_type i;

   typedef double _d_type;
  _d_type d;

   typedef double _integrator_type;
  _integrator_type integrator;

   typedef double _dervative_type;
  _dervative_type dervative;

   typedef double _proportional_type;
  _proportional_type proportional;




  typedef boost::shared_ptr< ::riverwatch_locomotion::PidControllerState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::riverwatch_locomotion::PidControllerState_<ContainerAllocator> const> ConstPtr;

}; // struct PidControllerState_

typedef ::riverwatch_locomotion::PidControllerState_<std::allocator<void> > PidControllerState;

typedef boost::shared_ptr< ::riverwatch_locomotion::PidControllerState > PidControllerStatePtr;
typedef boost::shared_ptr< ::riverwatch_locomotion::PidControllerState const> PidControllerStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::riverwatch_locomotion::PidControllerState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::riverwatch_locomotion::PidControllerState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace riverwatch_locomotion

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'riverwatch_locomotion': ['/home/dario/trsa_ws/src/new_fuerte_riverwatch/riverwatch_locomotion/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::riverwatch_locomotion::PidControllerState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::riverwatch_locomotion::PidControllerState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riverwatch_locomotion::PidControllerState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riverwatch_locomotion::PidControllerState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riverwatch_locomotion::PidControllerState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riverwatch_locomotion::PidControllerState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::riverwatch_locomotion::PidControllerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0adb4d4aa5b0e13fb1d12b5f48903d9f";
  }

  static const char* value(const ::riverwatch_locomotion::PidControllerState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0adb4d4aa5b0e13fULL;
  static const uint64_t static_value2 = 0xb1d12b5f48903d9fULL;
};

template<class ContainerAllocator>
struct DataType< ::riverwatch_locomotion::PidControllerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "riverwatch_locomotion/PidControllerState";
  }

  static const char* value(const ::riverwatch_locomotion::PidControllerState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::riverwatch_locomotion::PidControllerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string name\n\
bool PIDE\n\
float64 set_point\n\
float64 process_value\n\
float64 error\n\
float64 time_step\n\
float64 command\n\
float64 p\n\
float64 i\n\
float64 d\n\
float64 integrator\n\
float64 dervative\n\
float64 proportional\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::riverwatch_locomotion::PidControllerState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::riverwatch_locomotion::PidControllerState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.PIDE);
      stream.next(m.set_point);
      stream.next(m.process_value);
      stream.next(m.error);
      stream.next(m.time_step);
      stream.next(m.command);
      stream.next(m.p);
      stream.next(m.i);
      stream.next(m.d);
      stream.next(m.integrator);
      stream.next(m.dervative);
      stream.next(m.proportional);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PidControllerState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::riverwatch_locomotion::PidControllerState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::riverwatch_locomotion::PidControllerState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "PIDE: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.PIDE);
    s << indent << "set_point: ";
    Printer<double>::stream(s, indent + "  ", v.set_point);
    s << indent << "process_value: ";
    Printer<double>::stream(s, indent + "  ", v.process_value);
    s << indent << "error: ";
    Printer<double>::stream(s, indent + "  ", v.error);
    s << indent << "time_step: ";
    Printer<double>::stream(s, indent + "  ", v.time_step);
    s << indent << "command: ";
    Printer<double>::stream(s, indent + "  ", v.command);
    s << indent << "p: ";
    Printer<double>::stream(s, indent + "  ", v.p);
    s << indent << "i: ";
    Printer<double>::stream(s, indent + "  ", v.i);
    s << indent << "d: ";
    Printer<double>::stream(s, indent + "  ", v.d);
    s << indent << "integrator: ";
    Printer<double>::stream(s, indent + "  ", v.integrator);
    s << indent << "dervative: ";
    Printer<double>::stream(s, indent + "  ", v.dervative);
    s << indent << "proportional: ";
    Printer<double>::stream(s, indent + "  ", v.proportional);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIVERWATCH_LOCOMOTION_MESSAGE_PIDCONTROLLERSTATE_H
