(cl:defpackage tr5_kinematics-srv
  (:use )
  (:export
   "DOFORWARDKINEMATIC"
   "<DOFORWARDKINEMATIC-REQUEST>"
   "DOFORWARDKINEMATIC-REQUEST"
   "<DOFORWARDKINEMATIC-RESPONSE>"
   "DOFORWARDKINEMATIC-RESPONSE"
   "DOINVERSEKINEMATIC"
   "<DOINVERSEKINEMATIC-REQUEST>"
   "DOINVERSEKINEMATIC-REQUEST"
   "<DOINVERSEKINEMATIC-RESPONSE>"
   "DOINVERSEKINEMATIC-RESPONSE"
  ))

