// Generated by gencpp from file tr5_robot_controller/KinematicModeRequest.msg
// DO NOT EDIT!


#ifndef TR5_ROBOT_CONTROLLER_MESSAGE_KINEMATICMODEREQUEST_H
#define TR5_ROBOT_CONTROLLER_MESSAGE_KINEMATICMODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tr5_robot_controller
{
template <class ContainerAllocator>
struct KinematicModeRequest_
{
  typedef KinematicModeRequest_<ContainerAllocator> Type;

  KinematicModeRequest_()
    : mode(0)  {
    }
  KinematicModeRequest_(const ContainerAllocator& _alloc)
    : mode(0)  {
    }



   typedef uint8_t _mode_type;
  _mode_type mode;




  typedef boost::shared_ptr< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct KinematicModeRequest_

typedef ::tr5_robot_controller::KinematicModeRequest_<std::allocator<void> > KinematicModeRequest;

typedef boost::shared_ptr< ::tr5_robot_controller::KinematicModeRequest > KinematicModeRequestPtr;
typedef boost::shared_ptr< ::tr5_robot_controller::KinematicModeRequest const> KinematicModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tr5_robot_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89b81386720be1cd0ce7a3953fcd1b19";
  }

  static const char* value(const ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89b81386720be1cdULL;
  static const uint64_t static_value2 = 0x0ce7a3953fcd1b19ULL;
};

template<class ContainerAllocator>
struct DataType< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tr5_robot_controller/KinematicModeRequest";
  }

  static const char* value(const ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
uint8 mode\n\
";
  }

  static const char* value(const ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct KinematicModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tr5_robot_controller::KinematicModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TR5_ROBOT_CONTROLLER_MESSAGE_KINEMATICMODEREQUEST_H
